import Head from 'next/head'
import PageContainer from '@/components/PageContainer'
import ExperienceContainer from '@/components/ExperienceContainer'

export default function Experiencia() {
  return (
    <>
      <Head>
        <title>Experiência - Yasmin Carvalho</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContainer>
        <ExperienceContainer />
      </PageContainer>
    </>
  )
}
