import Head from 'next/head'
import PageContainer from '@/components/PageContainer'
import HomeAbout from '@/components/HomeAbout'
import Line from '@/components/Line'
import HomeProjects from '@/components/HomeProjects'
import HomeContact from '@/components/HomeContact'
import HomeRecommendations from '@/components/HomeRecommendations'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContainer>
        <HomeAbout />
        <Line />
        <HomeRecommendations />
        <Line />
        <HomeProjects />
        <Line />
        <HomeContact />
      </PageContainer>
    </>
  )
}
