import Head from 'next/head'
import PageContainer from '@/components/PageContainer'
import HomeAbout from '@/components/HomeAbout'
import Line from '@/components/Line'
import HomeProjects from '@/components/HomeProjects'
import Contact from '@/components/Contact'
import ExperienceContainer from '@/components/ExperienceContainer'
import useScrollReveal from '@/hooks/useScollReview'
import Footer from '@/components/Footer'

export default function Home() {
  useScrollReveal('.scroll-review-item', {
    duration: 1000,
    delay: 150,
    distance: '230px',
    scale: 1,
    easing: 'ease',

  });
  return (
    <>
      <Head>
        <title>Yasmin Carvalho</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer>
        <HomeAbout />
        <Line />
        <ExperienceContainer />
        <Line />
        <HomeProjects />
        <Line />
        <Footer/>
      </PageContainer>
    </>
  )
}
