import Head from 'next/head'
import Image from 'next/image'
import PageContainer from '@/components/PageContainer'

export default function Sobre() {
  return (
    <>
      <Head>
        <title>Sobre - Yasmin Carvalho</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContainer>
        Sobre
      </PageContainer>
    </>
  )
}
